### ISSUE TITLE
help-me

### ISSUE THREAD

**Issue by anso3000** [meishuu/tera-data-parser-js#6]
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_ACCEPT_FRIEND.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_ADD_FRIEND.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_ADD_INTER_PARTY_MATCH_POOL.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_ADD_TELEPORT_TO_POS_LIST.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_ASK_INTERACTIVE.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_CHANGE_MY_PROFILE.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_CHAT.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_CHECK_USERNAME.1.def", line 1
[protocol] load - parse warning: "count" or "offset" encountered, disabling implicit metatypes
    at "C:\Users\xxxx\Desktop\teste 2\tera-proxy\tera-proxy\node_modules\tera-data\protocol\C_CHECK_VERSION.1.def", line 1

**Comment by meishuu** [comment]
There was a little bug with this that was fixed in 59d4f0b, otherwise if you aren't writing def files then this warning doesn't matter for you.
